# Generated by Django 5.1.5 on 2025-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='decision',
            field=models.CharField(choices=[('none', 'None'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='none', max_length=15),
        ),
    ]
