# Generated by Django 5.1.5 on 2025-01-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hackathon_banner_hackathon_social_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='created_by',
        ),
    ]
