# Generated by Django 5.1.5 on 2025-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hackathon_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='banner',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='application_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='application_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_covers/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='members',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='prize_pool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_profiles/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='total_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='social_links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
