# Generated by Django 5.1.5 on 2025-01-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hackathon_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='interview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
