# Generated by Django 5.1.5 on 2025-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
