# Generated by Django 5.1.5 on 2025-01-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_interview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='none', max_length=15),
        ),
    ]
