# Generated by Django 5.1.5 on 2025-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='interview_status',
        ),
        migrations.AlterField(
            model_name='team',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
